show databases;
show databases;
use world;
use world;
show tables;
show tables;
desc city;
desc city;
select * from city;
select * from city;
select * from city where Countrycode = 'kor';
select * from city where countrycode = 'kor';
delete from city where id = 2; 
delete from city where id = 4;
select distinct name from city where countrycode = 'kor';
select distinct name from city where countrycode = 'kor';
select name,countrycode from city where countrycode = 'kor' and population >= 1000000;
select name,countrycode from city where countrycode = 'kor' and population >= 1000000;
select * from city where countrycode = 'kor' or countrycode = 'chn' or countrycode = 'jpn';
select * from city where countrycode = 'kor' or countrycode = 'chn' or coyntrycode = 'jpn';
select name from city where countrycode != 'kor' and population >= 1000000;
select name from city where countrycode != 'kor' and population >= 1000000;
select * from city where countrycode in ('kor','chn','jpn');
select * from city where countrycode in ('kor','chn','jpn');
select * from city where countrycode = 'kor' and (population >= 1000000 and population <= 5000000);
select * from city where countrycode = 'kor' and (population >= 1000000 and population <= 5000000);
select * from city where countrycode = 'kor' and (population between 1000000 and 5000000);
select * from city where countrycode = 'kor' order by population desc;
select * from city where countrycode = 'kor' order by population desc;
select population,countrycode from city order by countrycode,population desc;
select population,dountrycode from city order by countrycode,population desc;
select * from city where countrycode='kor' order by population desc limit 10;
select * from city where countrycode='kor' order by population desc limit 10;
select count(*) from city where countrycode = 'kor';
select count(*) from city where countrycode = 'kor';
select sum(population) from city where countrycode = 'kor';
select avg(population) from city where countrycode = 'kor';
select min(population) from city where countrycode = 'kor';
select length(name) from country;
select upper(mid(name,1,3))from country;
use user1220;
show tables;
desc manager;
desc add_option;
select * from add_option;
insert into add_option values(2,'ddong',true,true,'히히');
update add_option set bag = true where option_num = 2;
update add_option set message_card = '호호홓' where option_num = 2;
select * from product join add_option where option_num = product_num;